name: SAST Scan + SCA

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  sast-scan:
    strategy:
      fail-fast: false
      # Prevent running multiple FoD scans on same release simultaneously
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    env:
      SSC_URL: ${{vars.SSC_URL}}
      SSC_TOKEN: ${{secrets.SSC_TOKEN}}
      SC_SAST_TOKEN: ${{secrets.SC_SAST_TOKEN}}
      
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Java Version
        run: java --version

      - name: Set Scancentral Java Path
        run: echo "SCANCENTRAL_JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      # - name: Ping SSC server
      #   run: ping equal-rabbit-novel.ngrok-free.app

      # - name: Curl SSC URL
      #   run: curl -v -L https://equal-rabbit-novel.ngrok-free.app/ssc
        
      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v1
        with:
          tool-definitions: https://github.com/fortify/tool-definitions/releases/download/v1/tool-definitions.yaml.zip
          # export-path: true
          fcli: latest
          sc-client: 24.2.0
          # fod-uploader: latest
          # vuln-exporter: v2
          # bugtracker-utility: skip
          # debricked-cli: skip
      
      - name: Set Client Token for SAST Client
        run: sed -i "s|client_auth_token=.*|client_auth_token=${{secrets.SC_SAST_TOKEN}}|" $SC_CLIENT_INSTALL_DIR/Core/config/client.properties

      - name: Verify auth token
        run: cat $SC_CLIENT_INSTALL_DIR/Core/config/client.properties
        
      - name: Run SAST Client Update
        run: scancentral -url "https://equal-rabbit-novel.ngrok-free.app/scancentral-ctrl" update
        
      - name: Run SAST Scan using SAST Client
        if: true
        run: scancentral -url "https://equal-rabbit-novel.ngrok-free.app/scancentral-ctrl" start -block --output-file "sast.fpr" -log "sast.log" -diag "debug.log" -pi 10

      - name: Upload Scan Result to SSC
        run: |
          fcli ssc session login --url ${{vars.SSC_URL}} -t ${{secrets.SSC_TOKEN}}
          fcli ssc artifact upload --session=default --av="REACT:Feelio" --file="sast.fpr" --progress="simple" --log-level=debug
          fcli ssc session logout --session=default --no-revoke-token
      
      # - name: SC-SAST - Login once
      #   uses: fortify/github-action/internal/sc-sast-login@feat-1.3.0
      # - name: SSC - Login once
      #   uses: fortify/github-action/internal/ssc-login@feat-1.3.0
            
      - name: Run SAST Scan using ScancentralSAST
        if: false
        uses: fortify/github-action@v1
        with:
          sast-scan: true
        env:
          SSC_URL: ${{vars.SSC_URL}}
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          SSC_APPVERSION: NextJs-ReactNative:1.0
          SC_SAST_TOKEN: ${{secrets.SC_SAST_TOKEN}}
          SC_SAST_SENSOR_VERSION: 24.2.0
          DO_EXPORT: true
          DO_WAIT: true
          JOB_SUMMARY_ACTION_EXTRA_OPTS: --fs "Security Auditor View"
          
