name: SAST Scan + SCA

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  sast-scan:
    strategy:
      fail-fast: false
      # Prevent running multiple FoD scans on same release simultaneously
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      - name: Ping SSC server
        run: ping equal-rabbit-novel.ngrok-free.app

      - name: Curl SSC URL
        run: curl -v https://equal-rabbit-novel.ngrok-free.app/ssc
            
      - name: Run SAST Scan using ScancentralSAST
        if: false
        uses: fortify/github-action@v1.0.0
        with:
          sast-scan: true
        env:
          SSC_URL: ${{vars.SSC_URL}}
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          SSC_APPVERSION: NextJs-ReactNative:1.0
          SC_SAST_TOKEN: ${{secrets.SC_SAST_TOKEN}}
          SC_SAST_SENSOR_VERSION: 24.2.0
          DO_EXPORT: true
          DO_WAIT: true
          JOB_SUMMARY_ACTION_EXTRA_OPTS: --fs "Security Auditor View"
          
